site_name: PG-MCEDIF
nav:
    - Accueil: accueil.md
    - Code: code.md
    - Tutoriels: tutoriels.md
    - Ressources: ressources.md
    - Contact: contact.md
not_in_nav: |
    index.md
    contact/*
    code/*
theme:
    name: mkdocs
    custom_dir: custom_theme/
    locale: fr
    color_mode: dark
    nav_style: dark
    user_color_mode_toggle: false
    navigation_depth: 3
extra_css: [style.css]
plugins:
    - search
